version: 1

formatters:
  simple:
    format: "%(name)s - %(levelname)s - %(message)s"



handlers:

  terminal_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: simple

  file_handler:
    class: logging.FileHandler
    filename: response.log
    mode: w
    formatter: simple



loggers:

  Logger:
    level: INFO
    handlers: [terminal_handler]
    propagate: false

  Response Logger:
    level: INFO
    handlers: [file_handler]
    propagate: false

  LM:
    level: INFO
    handlers: [terminal_handler]
    propagate: false
